name: Python Flask App Workflow

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Ensure pip is up to date
        pip install -r requirements.txt  # Install dependencies

    - name: Run the Flask app
      run: |
        export FLASK_APP=app.py  # Specify your Python file
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}  # Pass the secret to the environment
        flask run --host=0.0.0.0 --port=5000
        